apiRules:
- include:
    uidRegex: ^DocFxForUnity
    type: Namespace
- include:
    uidRegex: ^JMRSDKExampleSnippets
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: ^JMRSDK
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace